#pragma once

#include <stdint.h>
#include <time.h>
#include <esp_camera.h>

#define DHT_PIN 13
#define LIGHT_PIN 14

#define IMAGE_INTERVAL_MS 3000
#define WEATHER_INTERVAL_MS 2000
#define LIGHT_UPDATE_INTERVAL_MS 1000
#define WIFI_RECONNECT_LOG_INTERVAL_MS 5000
#define WIFI_CONNECT_POLL_MS 500
#define WIFI_CONNECT_TIMEOUT_MS 60000
#define RESTART_IF_NOT_READY_MS 300000
#define CLOCK_SYNC_TIMEOUT_MS 20000
#define CLOCK_SYNC_POLL_MS 500
#define MIN_VALID_UNIX_TIME 1700000000

#define WSS_RECONNECT_INTERVAL_MS 5000
#define WSS_HEARTBEAT_INTERVAL_MS 15000
#define WSS_HEARTBEAT_TIMEOUT_MS 3000
#define WSS_HEARTBEAT_MISSED_COUNT 2
static constexpr char WSS_PATH[] = "/api/wss-devices/ws";

#define NTP_SERVER_1 "pool.ntp.org"
#define NTP_SERVER_2 "time.google.com"
#define NTP_SERVER_3 "time.windows.com"
#define TIME_ZONE "MST7MDT,M3.2.0,M11.1.0"

#define DEFAULT_AUTO_START_TIME {20, 0, 0}
#define DEFAULT_AUTO_END_TIME {22, 0, 0}
#define DEFAULT_LIGHT_MODE 2

struct CameraFrameSizeOption {
    const char *name;
    framesize_t value;
};

#define CAMERA_FRAME_SIZE FRAMESIZE_HQVGA
#define CAMERA_JPEG_QUALITY 10
#define CAMERA_MIN_JPEG_QUALITY 10
#define CAMERA_MAX_JPEG_QUALITY 26
static const CameraFrameSizeOption CAMERA_FRAME_SIZE_OPTIONS[] = {
    {"QQVGA", FRAMESIZE_QQVGA},
    {"HQVGA", FRAMESIZE_HQVGA},
    {"QVGA", FRAMESIZE_QVGA},
    {"VGA", FRAMESIZE_VGA},
    {"SVGA", FRAMESIZE_SVGA},
    {"XGA", FRAMESIZE_XGA},
    {"SXGA", FRAMESIZE_SXGA},
    {"UXGA", FRAMESIZE_UXGA},
};
#define CAMERA_XCLK_FREQ_HZ 20000000
#define CAMERA_FB_COUNT 1
#define CAMERA_GRAB_MODE CAMERA_GRAB_WHEN_EMPTY
#define CAMERA_VFLIP 0
#define CAMERA_HMIRROR 0
#define CAMERA_DAY_BRIGHTNESS 1
#define CAMERA_DAY_CONTRAST 0
#define CAMERA_DAY_SATURATION 0
#define CAMERA_DAY_AGC_GAIN 4
#define CAMERA_DAY_GAIN_CEILING GAINCEILING_4X
#define CAMERA_DAY_AEC2 0
#define CAMERA_NIGHT_BRIGHTNESS 2
#define CAMERA_NIGHT_CONTRAST 2
#define CAMERA_NIGHT_SATURATION -1
#define CAMERA_NIGHT_AGC_GAIN 30
#define CAMERA_NIGHT_GAIN_CEILING GAINCEILING_64X
#define CAMERA_NIGHT_AEC2 1
#define CAMERA_PIN_PWDN -1
#define CAMERA_PIN_RESET -1
#define CAMERA_PIN_XCLK 21
#define CAMERA_PIN_SIOD 26
#define CAMERA_PIN_SIOC 27
#define CAMERA_PIN_D7 35
#define CAMERA_PIN_D6 34
#define CAMERA_PIN_D5 39
#define CAMERA_PIN_D4 36
#define CAMERA_PIN_D3 19
#define CAMERA_PIN_D2 18
#define CAMERA_PIN_D1 5
#define CAMERA_PIN_D0 4
#define CAMERA_PIN_VSYNC 25
#define CAMERA_PIN_HREF 23
#define CAMERA_PIN_PCLK 22
